### ISSUE TITLE
Make SessionEntry LockDelay configurable

### ISSUE THREAD

**Issue by Hughlav** [dmitriyGarden/consul-leader-election#8]
It would be great to be able to set the LockDelay on the configuration and have that propagated to the Session Entry. I'd be happy to make the PR. 

https://github.com/dmitriyGarden/consul-leader-election/blob/master/election.go#L87-L90

**Comment by dmitriyGarden** [comment]
New release is available

**Comment by Hughlav** [comment]
Thank you!
